---
- name: Configuring a client machine to become a authrative DNS server client
  hosts: dns_clients 
  gather_facts: no
  vars:
    dns_ip:
      - 192.168.1.91
      - 192.168.1.127
      - 192.168.1.89
    resolver_file: "/etc/resolv.conf"
  tasks:
    - name: Configuring a resolve.conf file
      copy:
        content: |
          {% for item in dns_ip %}
          nameserver {{ item }}
          {% endfor %}
        dest: "{{ resolver_file }}"
        mode: "0644"

  

