---
- name: CONFIGURING A DNS MASTER, DNS SLAVE, DNS CACHE SERVER
  hosts:
    - master_dns
    - slave_dns
    - cache_dns
  vars:
    - master_config: 0
    - slave_config: 0
    - cache_config: 1
  tasks:
    - name: CONFIGURING A DNS MASTER SERVER
      include_role:
        name: bind-master-dns
      when: 
        - inventory_hostname in groups['master_dns']
        - master_config == true

    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

    - name: CONFIGURING A DNS SLAVE SERVER
      include_role:
        name: bind-slave-dns
      when: 
        - inventory_hostname in groups['slave_dns'] 
        - slave_config == true
  
    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

    - name: CONFIGURING A DNS CACHE SERVER
      include_role:
        name: bind-cache-dns
      when: 
        - inventory_hostname in groups['cache_dns'] 
        - cache_config == true
    
