---
- name: Installing a Required packages
  yum: 
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart named

- name: Including a zone vars
  include_vars: "{{ item }}"
  loop:
    - forward-zone-vars.yml
    - reverse-zone-vars.yml

- name: Configuring a bind configuration file
  template:
    src: named.conf.j2
    dest: "{{ conf_dir }}/named.conf"
    backup: true
  notify: restart named
  
- name: configuring a forward-zone files
  template:
    src: forward-zone.j2
    dest: "{{ zone_directory }}/{{ item.name }}-forward"
    mode: "0740"
    group: named
    backup: true
  loop: "{{ forward_zones }}"
  notify: restart named
  when: config_forward_zone == true

- name: configuring a reverse-zone files
  template:
    src: reverse-zone.j2
    dest: "{{ zone_directory }}/{{ item.name }}-reverse"
    mode: "0740"
    group: named
    backup: true
  loop: "{{ reverse_zones }}"
  notify: restart named
  when: config_reverse_zone == true

- name: Configuring a SELINUX
  selinux:
    policy: targeted
    state: permissive

- name: Restarting firewalld....
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: Config firewalle rules




