---
- name: Installing a Required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart named

- name: Including a zone variable files
  include_vars: zone_vars.yml

- name: Configuring a configuration file
  template:
    src: named.conf.j2
    dest: "{{ conf_dir }}/named.conf"
  notify: restart named

- name: Configuring a SELINUX
  selinux:
    policy: targeted
    state: permissive

- name: Restarting a firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: Configure firewalle rules
