---
- name: Installing a required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart named

- name: Configuring a bind cache server
  template:
    src: named.conf.j2
    dest: /etc/named.conf
  notify: restart named

- name: Configuring a SELINUX
  selinux:
    policy: targeted
    state: permissive

- name: Starting a firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: Config firewall rules
  
