---
- name: Installing required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart unbound

- name: Configure the unbound server
  template:
    src: cache.conf.j2
    dest: "{{ unbound_conf }}"
  notify: restart unbound

- name: Configuring a selinux
  selinux:
    policy: targeted
    state: permissive

- name: starting firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: config firewall rules



